<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$repositories = $client->api('user')->repositories('Nekrofage');

//print_r($repositories);

$commits = $client->api('repo')->commits()->all('Nekrofage', 'drone', array('sha' => 'master'));

print_r(count($commits));
